version: 0.0
os: linux
files:
  - source: /build/libs/reaction-game.jar
    destination: /home/ubuntu/

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
