### Create Admin Player
POST {{host}}/players HTTP/1.1
Content-Type: application/json
X-PLAYER-TOKEN: {{x-player-token}}

{
  "name": "ADMIN",
  "admin": true
}

### Create Player
POST {{host}}/players HTTP/1.1
Content-Type: application/json
X-PLAYER-TOKEN: {{x-player-token}}

{
  "name": "PLAYER",
  "admin": false
}

### Get Players
GET {{host}}/players HTTP/1.1
Content-Type: application/json
X-PLAYER-TOKEN: {{x-player-token}}

### Delete Player
< {%
    request.variables.set("playerId", "1")
%}
DELETE {{host}}/players/{{playerId}} HTTP/1.1
Content-Type: application/json
X-PLAYER-TOKEN: {{x-player-token}}

### Create Session
< {%
    const PLAY_TIME_IN_MINUTES = 10;

    const baseTime = new Date().getTime();
    const now = new Date(baseTime + 9 * 60 * 60 * 1000); // adjust to UTC+9
    const playTimeInMillis = PLAY_TIME_IN_MINUTES * 60 * 1000;
    request.variables.set("startDate", now.toISOString())
    request.variables.set("endDate", new Date(now.getTime() + playTimeInMillis).toISOString())
%}
POST {{host}}/sessions HTTP/1.1
Content-Type: application/json
X-PLAYER-TOKEN: {{x-player-token}}

{
    "title": "Test Session2",
    "startDate": "{{startDate}}",
    "endDate": "{{endDate}}"
}

### Get Sessions
GET {{host}}/sessions HTTP/1.1
Content-Type: application/json
X-PLAYER-TOKEN: {{x-player-token}}

### Get Session
< {%
    request.variables.set("sessionId", "1")
%}
GET {{host}}/sessions/{{sessionId}} HTTP/1.1
Content-Type: application/json
X-PLAYER-TOKEN: {{x-player-token}}

### Delete Session
< {%
    request.variables.set("sessionId", "1")
%}
DELETE {{host}}/sessions/{{sessionId}} HTTP/1.1
Content-Type: application/json
X-PLAYER-TOKEN: {{x-player-token}}

### Get Session Status
< {%
    request.variables.set("sessionId", "1")
%}
GET {{host}}/sessions/{{sessionId}}/status HTTP/1.1
Content-Type: application/json
X-PLAYER-TOKEN: {{x-player-token}}

